### ISSUE TITLE
Very Nice CMS

### ISSUE THREAD

**Issue by tyeeman** [brimstone/mdcms#1]
Yes, I too like mdwiki and I like this one too! I can have an infinite number of content areas by just making lots of .md files and placing them in any div in any generic web template, cool! Point to note though, I had to place the javascript line right at the end of the div if I was wanting it to read a .md file. If I placed the .js line at the top or bottom of the html file, it did not work! Do you know why?

**Comment by brimstone** [comment]
Can you post the a link to a gist or the actual html page and one of the markdown files please?

**Comment by tyeeman** [comment]
This is what I had to do 

`<div id="content" data-marked="#" data-default="README.md"> Loading...<br/>
        Javascript must be enabled.</div>
        <script src="mdcms.js"></script`

I guess `<script src="mdcms.js"></script>` is supposed to be put in the `<head>` area and it should work ok?

Check out these pages -
this works - script line put at end of  `<div>` --> `http://site.net/mdcms/index.html`
this does not - script line put in `<head>` -->  `http://site.net/mdcms/index2.html`

**Comment by brimstone** [comment]
ah! I see the problem. I was loading javascripts after the rest of the page, in accordance with "Best Practices" I see that you want to load the javascript in the head, so I've made mdcms trigger once the window is loaded instead. This seems to work in my testing. Please try it and reopen this if it doesn't work for you.
